spring.application.name=Ferreteria

#Configuraciones generales de la BD
spring.datasource.url=jdbc:mysql://localhost:3306/ferreteria?connectionTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Configuraciones JPA
spring.jpa.hibernate.ddl-auto=update